version: '3.7'
services:
  login-service:
    image: boxboys-login-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: boxboys-login-service
    ports:
      - 5000:80
      - 5001:443

  selleraccount-service:
    image: boxboys-selleraccount-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: boxboys-selleraccount-service
    ports:
      - 5010:80
      - 5011:443

  search-service:
    image: boxboys-search-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: boxboys-search-service
    ports:
      - 5012:80
      - 5013:443    
      
  frontend:
    image: boxboys-frontend:latest
    ports: 
      - 3010:3000
    stdin_open: true
    container_name: boxboys-frontend
    depends_on: 
      - "login-service"
      - "selleraccount-service"
      - "search-service"
    
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=boxboyspackaging@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ILoveBoxes1
    ports:
      - "5050:80"