#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["UpdateSaveDB/UpdateSaveDB.csproj", "UpdateSaveDB/"]
COPY ["SharedClasses", "SharedClasses"]
RUN dotnet restore "./UpdateSaveDB/UpdateSaveDB.csproj"
COPY . .

WORKDIR "/src/SharedClasses"
RUN dotnet build "SharedClasses.csproj" -c Release -o ./bin/Debug/netcoreapp3.1/

WORKDIR "/src/UpdateSaveDB"
RUN dotnet build "UpdateSaveDB.csproj" -c Release -o /app/build


FROM build AS publish
RUN dotnet publish "UpdateSaveDB.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UpdateSaveDB.dll"]